#!/bin/bash -e
# Borrowed from here: https://github.com/tgockel/nginxconfig/blob/e78775850b9094cbea294d084408664d9ef2ae80/config/publish-doxygen
# Detailed description is here: http://blog.gockelhut.com/2014/09/automatic-documentation-publishing-with.html

# Settings
REPO_PATH=git@github.com:UNN-VMK-Software/agile-course-theory.git
GHPAGES_PATH=agile-course-ghpages
HTML_PATH=slides
COMMIT_USER="Slides Generator"
COMMIT_EMAIL="kirill.kornyakov+travis-ci@gmail.com"
CHANGESET=$(git rev-parse --verify HEAD)

# Get a clean version of the HTML documentation repo.
cd ..
git clone -b gh-pages "${REPO_PATH}" --single-branch ${GHPAGES_PATH}

# rm all the files through git to prevent stale files.
cd ${GHPAGES_PATH}/${HTML_PATH}
git rm -rf .

# Generate the HTML documentation.
# Kornyakov: in our case it is already generated, so we only copy it
# make doxygen
cp ../../agile-course-theory/slides-rendered/* ./

# Create and commit the documentation repo.
# cd ${HTML_PATH}
git add .
git config user.name "${COMMIT_USER}"
git config user.email "${COMMIT_EMAIL}"
git commit -m "Automated slides build for changeset ${CHANGESET}."
git push origin gh-pages
# cd -
